language: python
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-enchant
install:
  - pip install -e .
  - pip install -r requirements.txt
script: make test
after_success:
  - coveralls
